Route123_BerryMaster_upstairs_MapScripts::
	.byte 0


ROUTE_123_BERRYMASTERSHOUSE_STUPID_TOGEPI_DOLL::
# 4 "data/maps/Route123_BerryMaster_upstairs/scripts.pory"
	lockall
# 5 "data/maps/Route123_BerryMaster_upstairs/scripts.pory"
	msgbox ROUTE_123_BERRYMASTERSHOUSE_STUPID_TOGEPI_DOLL_Text_0
# 6 "data/maps/Route123_BerryMaster_upstairs/scripts.pory"
	waitmessage
# 7 "data/maps/Route123_BerryMaster_upstairs/scripts.pory"
	releaseall
	return


ROUTE_123_BERRYMASTERSHOUSE_STUPID_TOGEPI_DOLL_Text_0:
# 5 "data/maps/Route123_BerryMaster_upstairs/scripts.pory"
	.string "KHWFIRHIHSKH$"
